.\"Created with GNOME Manpages Editor
.\"http://gmanedit.sourceforge.net
.\"Sergio Rua <srua@gpul.org>
.\"
.\"
.\" Geeqie manual page.
.\" (C)2004 John Ellis <johne@verizon.net>
.\"
.\" This document is free to modify and distribute.
.\"
.TH geeqie 1 "Geeqie"

.SH NAME
Geeqie \- GTK based multiformat image viewer
.SH SYNOPSIS
.B geeqie
.RI [ options ] 
.RI [ path ]
.br

.SH DESCRIPTION
\fBGeeqie\fP is an interactive GTK based image viewer that supports multiple image formats, zooming, panning, thumbnails and sorting images into collections.

.SH OPTIONS
.B
.IP \+t,\-\-with\-tools
Force the toolbox to be shown.
.br
.B
.IP \-t,\-\-without\-tools
Force the toolbox to be hidden.
.br
.B
.IP \-f,\-\-fullscreen
Start in full screen mode.
.br
.B
.IP \-s,\-\-slideshow
Start in slideshow mode.
.br
.B
.IP \-l,\-\-list[files...][collections...]
Open collection window for command line files.
.br
.B
.IP \-\-blank
Start with blank file list.
.br
.B
.IP \-\-geometry=XxY+XOFF+YOFF
Set main window location.
.br
.B
.IP \-r,\-\-remote
Send following commands to open window.
.br
.B
.IP \-rh,\-\-remote-help
Print remote command list.
.br
.B
.IP \-\-debug[=level]
Turn on debugging output.
.br
.B
.IP \-g:<regexp>,\-\-grep:<regexp>
Filter debug output.
.br
.B
.IP \+w,\-\-show-log-window
Show log window.
.br
.B
.IP \-o:<FILE>,\-\-log-file:<FILE>
Save log data to FILE.
.br
.B
.IP \-v,\-\-version
Print version.
.br
.B
.IP \-h,\-\-help
Print command line options.

.SH REMOTE OPTIONS
.B
.IP \-n,\-\-next
Next image.
.br
.B
.IP \-b,\-\-back
Previous image.
.br
.B
.IP \-\-first
First image.
.br
.B
.IP \-\-last
Last image.
.br
.B
.IP \-f,\-\-fullscreen
Toggle full screen.
.br
.B
.IP \-fs,\-\-fullscreen-start
Start full screen.
.br
.B
.IP \-fS,\-\-fullscreen-stop
Stop full screen.
.br
.B
.IP \-s,\-\-slideshow
Toggle slideshow.
.br
.B
.IP \-ss,\-\-slideshow-start
Start slideshow.
.br
.B
.IP \-sS,\-\-slideshow-stop
Stop slideshow.
.br
.B
.IP \-\-slideshow-recurse:<FOLDER>
Start recursive slide show in FOLDER.
.br
.B
.IP \-d<[HRS:][MINS:][N][.M]>,\-\-delay=<[hrs:][mins][N][.M]>
Set slide show delay to Hrs Mins N.M seconds.
.br
.B
.IP \+t,\-\-tools-show
Show tools.
.br
.B
.IP \-t,\-\-tools-hide
Hide tools.
.br
.B
.IP \-q,\-\-quit
Quit.
.br
.B
.IP \-\-config-load:<FILE>
Load configuration from FILE.
.br
.B
.IP \-\-get-sidecars:<FILE>
Get list of sidecars of FILE.
.br
.B
.IP \-\-get-destination:<FILE>
Get destination path of FILE.
.br
.B
.IP \-\-file:<FILE>
Open FILE, bring Geeqie window to the top.
.br
.B
.IP \-\-File:<FILE>
Open FILE, do not bring Geeqie window to the top.
.br
.B
.IP \-\-tell
Print filename of current image.
.br
.B
.IP \-\-view:<FILE>
Open FILE in new window.
.br
.B
.IP \-\-list-clear
Clear command line collection list.
.br
.B
.IP \-\-list-add:<FILE>
Add FILE to command line collection list.
.br
.B
.IP raise
Bring the Geeqie window to the top.
.br
.B
.IP \-ct:clear|clean,\-\-cache-thumbs:clear|clean
Clear or clean thumbnail cache.
.br
.B
.IP \-cs:clear|clean,\-\-cache-shared:clear|clean
Clear or clean shared thumbnail cache.
.br
.B
.IP \-cm,\-\-cache-metadata
Clean metadata cache.
.br
.B
.IP \-cr:<folder>,\-\-cache-render:<folder>
Render thumbnails.
.br
.B
.IP \-crr:<folder>,\-\-cache-render-recurse:<folder>
Render thumbnails recursively.
.br
.B
.IP \-crs:<folder>,\-\-cache-render-shared:<folder>
Render thumbnails (see Help).
.br
.B
.IP \-crsr:<folder>,\-\-cache-render-shared-recurse:<folder>
Render thumbnails recursively (see Help).
.br
.B
.IP \-\-lua:<FILE>,<lua-script>
Run lua script on FILE.
.br

.SH USAGE
Key naming is similar to that of \fBemacs\fP(1): \fIC-key\fP indicates that control should be held, and key should be pressed; \fIS-key\fP  indicates that shift should be held and key should be pressed; these two can be combined, also, into \fIC-S-key\fP.
.B
.IP left-mouse-click
(on image) next image
.br
.B
.IP middle-mouse-click
(on image) previous image
.br
.B
.IP right-mouse
context menu
.br
.B
.IP middle-mouse-drag
drag and drop operations
.br
.B
.IP mouse-wheel
(on image) Changes to the next or previous image, or if option is enabled, scrolls the image vertically.
.br
.B
.IP mouse-wheel+Shift-key
(on image) Inverts the mouse wheel behavior between scrolling image or changing image.
.br
.B
.IP mouse-wheel+Control-key
(on image) Zooms the image in and out.
.br
.SS GENERAL  KEYS
.B
.IP PageDown
next image
.br
.B
.IP PageUp
previous image
.br
.B
.IP Home                             
first image in list
.br
.B
.IP End
last image in list
.br
.B
.IP Tab
tab completion in path entry window
.br
.B
.IP Escape
cancel completion in path entry window or stop generating thumbnails
.br
.SS IMAGE KEYS
Keys that are valid when the image part of the window is focused.
.B
.IP Arrows
pan image
.br
.B
.IP Shift+Arrows
pan image faster
.br
.B
.IP Space,N
next image
.br
.B
.IP Backspace,B
previous image
.br
.SS FILE RELATED KEYS
.B
.IP C
new empty collection
.br
.B
.IP O
open collection
.br
.B
.IP D
open the Find Duplicates window
.br
.B
.IP C-F
new folder
.br
.B
.IP C-C
copy file
.br
.B
.IP C-M
move file
.br
.B
.IP C-R
rename file
.br
.B
.IP C-D,Delete
delete file
.br
.B
.IP C-N
new window
.br
.B
.IP C-W
close window
.br
.B
.IP C-Q
quit
.br
.SS EDIT MENU RELATED KEYS
.B
.IP C-1,2..9,0
run external editor
.br
.B
.IP C-A
select all files
.br
.B
.IP C-S-A
unselect all files
.br
.B
.IP C-O
go to the Configuration window
.br
.B
.IP C-P
display image properties
.br
.B
.IP ]
rotate image clockwise
.br
.B
.IP [
rotate image counterclockwise
.br
.B
.IP S-R
rotate image 180 degrees
.br
.B
.IP S-M
mirror image (horizontal)
.br
.B
.IP S-F
flip image (vertical)
.br
.SS VIEW MENU RELATED KEYS
.B
.IP +,=
zoom in
.br
.B
.IP -
zoom out
.br
.B
.IP Z,KeyPad-/
zoom to original size
.br
.B
.IP X,KeyPad-*
zoom to fit window
.br
.B
.IP 1,2,3,4
zoom in to X scale factor
.br
.B
.IP 9,8,7
zoom to \-2, \-3, \-4, respectively
.br
.B
.IP T
toggle thumbnail display
.br
.B
.IP C-L
display files in list format
.br
.B
.IP C-I
display files in icon format
.br
.B
.IP C-T
toggle tree view for directories
.br
.B
.IP R
refresh file list
.br
.B
.IP L
toggle floating of file selection area
.br
.B
.IP H
toggle hiding of file selection area
.br
.B
.IP F,V
toggle full-screen mode
.br
.B
.IP S
toggle slide-show mode
.br
.B
.IP P
toggle pause of slideshow
.br
.B
.IP C-E
toggle display of exif sidebar
.br
.B
.IP C-S
toggle display of sort manager
.br
.SS COLLECTION WINDOW KEYS
.B
.IP Arrows
move selection
.br
.B
.IP Shift+Arrows
select multiple images
.br
.B
.IP Control+Arrows
move selector without changing selection
.br
.B
.IP Space
select the image under the selector
.br
.B
.IP Control+Space
toggle selection of the image under the selector
.br
.B
.IP Home
move selector to the top image
.br
.B
.IP End
move selector to bottom image
.br
Adding Shift or Control to Home and End has a similar effect as adding them to the arrows.
.B
.IP C-A
select all images
.br
.B
.IP C-S-A
unselect all images
.br
.B
.IP Delete
remove image form collection (does not delete the file)
.br
.B
.IP C-L
add images to collection form main file list
.br
.B
.IP N
sort collection by name
.br
.B
.IP D
sort collection by date
.br
.B
.IP B
sort collection by file size
.br
.B
.IP P
sort collection by pathname
.br
.B
.IP I
sort collection by name numerically (*)
.br
.B
.IP Enter
view image under selector in the main image window
.br
.B
.IP V
view image under selector in new window
.br
.B
.IP C-1,2..9,0
open selected image(s) in external editor
.br
.B
.IP S
save collection
.br
.B
.IP C-S
save collection as
.br
.B
.IP A
append current collection to existing collection
.br
.B
.IP C-C
copy selected files
.br
.B
.IP C-M
move selected files
.br
.B
.IP C-R
rename selected files
.br
.B
.IP C-D
delete selected files
.br
.B
.IP C-W
close window
.br
.SS DUPLICATES WINDOW KEYS
.B
.IP C-A
select all images
.br
.B
.IP C-S-A
unselect all images
.br
.B
.IP 1
select group 1 images
.br
.B
.IP 2
select group 2 images
.br
.B
.IP C-L
add images from main window file list
.br
.B
.IP C
add selected images to new collection
.br
.B
.IP Delete
remove selected images from list
.br
.B
.IP C-Delete
clear window
.br
.B
.IP Enter
view image with focus in main window
.br
.B
.IP V
view image with focus in new window
.br
.B
.IP C-1,2..9,0
open selected image(s) in editor
.br
.B
.IP C-P
display properties window for selected images
.br
.B
.IP C-C
copy selected files
.br
.B
.IP C-M
move selected files
.br
.B
.IP C-R
rename selected files
.br
.B
.IP C-D
delete selected files
.br
.B
.IP C-W
close window
.br


.SH LICENSE
Copyright (C) 1999-2004 by John Ellis.
Copyright (C) 2004-2017 by The Geeqie Team.
Use this software at your own risk!  
This software released under the GNU General Public License. Please read the COPYING file for more information.
.SH BUGS
Please send bug reports and feedback to https://github.com/BestImageViewer/geeqie/issues
.SH AUTHOR
.B John Ellis
<johne@verizon.net>
.br
Manpage originally prepared by
.B Nick Rusnov
<nick@grawk.net>
